### ISSUE TITLE
Parser doesn't allow singlequote in html attribute

### ISSUE THREAD

**Issue by RamBoFe** [zackad/prettier-plugin-twig#62] opened 2024-09-16 09:28 UTC
For example the parser bug with this line : 

`<img class='img img-responsive' src='{{ asset('img/logo/logo.png') }}' />`

Here the message : 

```
Error: ERROR: Expected an Identifier
   8 |   <div class="login-box">
   9 |     <div class="login-logo">
> 10 |       <a href='{{ path('core_back_default_index') }}'><img class='img img-responsive" src="{{ asset('img/logo/logo.png') }}' />
     |               ^
  11 |       </a>
  12 |     </div>
  13 |     <div class="login-box-body">

Expected a valid attribute name, but instead found "'", which is not part of a valid attribute name.
    at TokenStream.error (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:129:24)
    at new TokenStream (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:59:18)
    at createConfiguredParser (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/@zackad/prettier-plugin-twig/src/parser.js:51:9)
    at Object.parse (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/@zackad/prettier-plugin-twig/src/parser.js:81:20)
    at parse4 (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/prettier/index.mjs:20685:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coreFormat (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/prettier/index.mjs:21146:7)
    at async formatWithCursor (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/prettier/index.mjs:21348:14)
    at async Module.format2 (file:///tmp/8907fc23-d5ec-42d0-b616-7dc7891adb0f/node_modules/prettier/index.mjs:22733:25)
Process finished with exit code -1
```

A trace of this problem can be found here : [trivago/#49](https://github.com/trivago/prettier-plugin-twig-melody/issues/49)

If we change the single quotes to double quotes it works but wouldn't it be desirable for the parser to support this change?

**Comment by zackad** [comment] 2024-10-02 02:25
I'm hesitate to allow single quote on html attribute. From [this comment](https://github.com/zackad/prettier-plugin-twig/issues/50#issuecomment-2298766933), it is difficult to allow single quote on html attriute containing twig expression e.g
```twig
<a href='{{ path('homepage') }}'>Home</a>
```
As you can see, there's no clear distinction where the start/end of string expression delimited by single quote.

Ultimately, prettier is _opiniated_ code formatter. I think we should impose our own code style if supporting multiple style prove to be difficult. Of course pull request implementing this feature are always welcomed.

**Comment by renestalder** [comment] 2024-10-02 08:47
I mean, does it not work like that?

```twig
<a href='{{ path("homepage") }}'>Home</a>
```

I don't think this is related to prettier. It's pretty clear to me that the syntax can't work if both expressions use single-quote. So you either write:

```twig
<a href='{{ path("homepage") }}'>Home</a>
```

or

```twig
<a href='{{ path("homepage") }}'>Home</a>
```

And if both those expressions are correctly handled by the prettier plugin and not false-positive changed, I think the behaviour is correct.

As I used this plugin even in the Trivago version earlier on pretty big codebases, and now also the new version, I feel a bit like it already works correctly if the correct syntax is used.

**Comment by zackad** [comment] 2024-10-02 09:56
> I mean, does it not work like that?
> 
> ```
> <a href='{{ path("homepage") }}'>Home</a>
> ```
> 
> I don't think this is related to prettier. It's pretty clear to me that the syntax can't work if both expressions use single-quote. So you either write:
> 
> ```
> <a href='{{ path("homepage") }}'>Home</a>
> ```
> 
> or
> 
> ```
> <a href="{{ path('homepage') }}">Home</a>
> ```
> 
> And if both those expressions are correctly handled by the prettier plugin and not false-positive changed, I think the behaviour is correct.

This is the correct solution. Either use single quote on html atrribute and double quote on twig expression. Or use double quote on html attribute and single quote on twig expression.

**Comment by zackad** [comment] 2024-10-02 09:58
Closing this issue since the plugin is working as intended.

**Closed by zackad** 2024-10-02 09:58 UTC
Labels: wontfix
